server:
  port: 8050
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://stg-discovery.excellencekits.com:8761/eureka}
spring:
  application:
    name: services-cloud-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allow-credentials: true
            allowedOrigins: "http://localhost:3001"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: accountant
          uri: lb://accountant
          predicates:
            - Path=/accountant/**
        - id: notification
          uri: lb://notification
          predicates:
            - Path=/notification/**

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: fast-id
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://stg-services.excellencekits.com/login/oauth2/code/gateway"
            scope: openid
        provider:
          my-provider:
            issuer-uri: http://stg-oauth2.excellencekits.com
jwt:
  auth:
    converter:
      resource-id: web_front_auth
      principal-attribute: preferred_username


app:
  cors:
    allowed-origins: http://localserver:3001
